### ISSUE TITLE
how can I stop the queue better?

### ISSUE THREAD

**Issue by Kamomede** [rknell/dart_queue#19]
After the queue calls the cancel method, it cannot re-add a new future to the queue because a QueueCancelledException will be reported after adding it. So how can I stop the queue better?

**Comment by rknell** [comment]
When you call cancel the queue object gets cleaned up and disposed. So you probably want to make another one if you intend to cancel it and then add futures to queue.

You could check everywhere or wrap try catch blocks around everything, but the easiest thing to do would probably just to make the variable that holds the queue object not final, and when you call cancel immediately set the variable to a new queue object.

I'll close this out but let me know if you have any more questions.

**Comment by BodenTide** [comment]
Will you consider adding a clear method in the future, which means retaining the queue and clearing the future in it?

**Comment by Kamomede** [comment]
will you consider adding a method to clear the tasks in the queue in the future? That is to keep the queue and clear the future in it.
